---
- name: Install tomcat8
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: no
  tasks:
   - name: Install tomcat
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
